# NumPy indexing and Selection

In [3]:
import numpy as np

In [4]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [7]:
arr[:]=99
arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

## 2D array

In [9]:
arr_2d = np.array(([1,2,3],[4,5,6],[7,8,9]))
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arr_2d[1,0]

4

In [13]:
#从第 1位开始，取两行
arr_2d[:2,1:]

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
arr2d = np.zeros((10,10))

In [19]:
arr_length = arr2d.shape[1]

In [20]:
for i in range(arr_length):
    arr2d[i][i] = i
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 2., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 3., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 4., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 5., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 6., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 7., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 8., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 9.]])

In [21]:
arr2d[[2,4,6,8]]

array([[0., 0., 2., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 4., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 6., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 8., 0.]])

In [23]:
# allow in any order
arr2d[[9,1,3]]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 9.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 3., 0., 0., 0., 0., 0., 0.]])

## selection

In [24]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [26]:
bool_arr = arr>4

In [27]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [28]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [29]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
x=2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])