# NumPy indexing and Selection

In [3]:
import numpy as np

In [4]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [7]:
arr[:]=99
arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

## 2D array

In [9]:
arr_2d = np.array(([1,2,3],[4,5,6],[7,8,9]))
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arr_2d[1,0]

4

In [13]:
#从第 1位开始，取两行
arr_2d[:2,1:]

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
arr2d = np.zeros((10,10))

In [19]:
arr_length = arr2d.shape[1]

In [20]:
for i in range(arr_length):
    arr2d[i][i] = i
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 2., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 3., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 4., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 5., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 6., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 7., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 8., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 9.]])

In [21]:
arr2d[[2,4,6,8]]

array([[0., 0., 2., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 4., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 6., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 8., 0.]])

In [23]:
# allow in any order
arr2d[[9,1,3]]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 9.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 3., 0., 0., 0., 0., 0., 0.]])

## selection

In [24]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [26]:
bool_arr = arr>4

In [27]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [28]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [29]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
x=2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

## numPy operations

In [31]:
arr = np.arange(1,11)
arr+arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [32]:
arr * arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [33]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [34]:
arr/arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [35]:
1/arr

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ])

In [36]:
arr**3

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000])

In [37]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [38]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [39]:
np.max(arr)

10

In [40]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

# eye

In [41]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
#Use NumPy to generate a random number between 0 and 1
np.random.randn(1)

array([0.79322222])

### Create an array of 20 linearly spaced points between 0 and 1:


In [45]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [46]:
np.random.randn(25)

array([-0.90029956, -0.4228457 ,  0.42819039,  0.37666928, -0.74498916,
        1.84443614, -0.51845386, -1.3184422 , -0.72025945, -0.70448354,
        1.66577455, -1.49395399,  0.94177347,  0.35412064, -1.42950045,
        0.94116096,  0.36679297,  0.61638649,  1.36340788, -0.89683202,
       -0.99885139, -0.48596366, -1.51401063, -1.64261566, -0.45949903])

### Sum of columns and rows

In [48]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [49]:
# sum of columns
mat.sum(axis = 0)

array([55, 60, 65, 70, 75])

In [50]:
# sum of rows
mat.sum(axis = 1)

array([ 15,  40,  65,  90, 115])